encoder:
  name: 'Fossil' 
  weight_path: '/nethome/recpinfo/users/fibz/data/checkpoints/frozen fossil 1k/ckpt/11999/consolidated_model/pytorch_model.bin'
  config_path: 'dinov3/configs/train/dinov3_vitl16_geo.yaml' 
  size: 512 # image size
decoder:
  # name: "Qwen/Qwen3-4B-Thinking-2507"
  name: "Qwen/Qwen3-0.6B"
  lora_rank: 16
  lora_alpha : 32
  apply_lora: True
multimodal: 'mapper:20' # mapper, merger, projector,
train:
  batch_size: 16
  stage1:
    # train the multi modal bridge only
    learning_rate: 0.001
    epochs: 1
  stage2:
    # end to end train
    frozen_encoder: True
    learning_rate: 0.0002
    epochs: 4
data:
  root: "/nethome/atena_projetos/fibz/images"
  train: "/nethome/atena_projetos/fibz/data/Dataset/simple_conversation/conv_train.json"
  test: "/nethome/atena_projetos/fibz/data/Dataset/simple_conversation/conv_test.json"
save_path: "/nethome/recpinfo/users/fibz/data/checkpoints/fossil_vl"

# "facebook/dinov3-vitl16-pretrain-lvd1689m"