# -*- coding: utf-8 -*-
"""DINOv3 pca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rLIiTaGbpcDGYdatSwmDI4uFEHxLPBE

# Computing the PCA of a Foreground Object
We show in our paper many figures with object parts colored like rainbows. These visualizations are obtained by computing a PCA of patch features on the foreground object. This is what we will compute in this tutorial! Let's start by loading some pre-requisites.

### Setup

Let's start by loading some pre-requisites and checking the DINOv3 repository location:
- `local` if `DINOV3_LOCATION` environment variable was set to work with a local version of DINOv3 repository;
- `github` if the code should be loaded via torch hub.
"""

import pickle
import os
import urllib

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

from transformers import TorchAoConfig, AutoImageProcessor, AutoModel
from torchao.quantization import Int4WeightOnlyConfig
from transformers.image_utils import load_image

import torch
import torchvision.transforms.functional as TF
from sklearn.decomposition import PCA
from scipy import signal
from load_model import load_trained_model

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)
PATCH_SIZE = 16
IMAGE_SIZE = 512

def load_model(model_name="facebook/dinov3-vitl16-pretrain-lvd1689m"):
    model = AutoModel.from_pretrained(
        model_name,
        device_map="auto",
    )

    return model


def resize_transform(mask_image: Image, image_size: int = IMAGE_SIZE, patch_size: int = PATCH_SIZE,) -> torch.Tensor:
    w, h = mask_image.size
    h_patches = int(image_size / patch_size)
    w_patches = int((w * image_size) / (h * patch_size))
    image_resized = TF.to_tensor(TF.resize(mask_image, (h_patches * patch_size, w_patches * patch_size)))
    return TF.normalize(image_resized, mean=IMAGENET_MEAN, std=IMAGENET_STD)


def show_pca(x, image, save_name):
    pca = PCA(n_components=3)
    pca.fit(x.numpy())
    w, h = image.size
    h_patches = int(IMAGE_SIZE / PATCH_SIZE)
    w_patches = int((w * IMAGE_SIZE) / (h * PATCH_SIZE))
    projected_image = torch.from_numpy(pca.transform(x.numpy())).view(h_patches, w_patches, 3)
    # multiply by 2.0 and pass through a sigmoid to get vibrant colors
    projected_image = torch.nn.functional.sigmoid(projected_image.mul(2.0)).permute(2, 0, 1)

    # enjoy
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 12))

    ax1.imshow(image)
    ax1.set_title("Original Image")
    ax1.axis('off')

    ax2.imshow(projected_image.permute(1, 2, 0))
    ax2.set_title("PCA Visualization")
    ax2.axis('off')

    plt.figure(dpi=300)
    fig.savefig(save_name)


def show_clssim(x, cls, image, save_name):
    """### Visualize cls similarity
    Check the similarity between cls global feature and dense features
    """
    w, h = image.size
    h_patches = int(IMAGE_SIZE / PATCH_SIZE)
    w_patches = int((w * IMAGE_SIZE) / (h * PATCH_SIZE))

    with torch.inference_mode():
        x /= torch.norm(x, dim=-1, keepdim=True)
        cls /= torch.norm(cls, dim=-1, keepdim=True)
        similarities = x @ cls.T
        similarities = similarities.numpy()
        similarities += np.abs(np.min(similarities))
        similarities /= np.max(similarities)
        # print(np.max(similarities), np.min(similarities))

        projected_image = torch.from_numpy(similarities).view(h_patches, w_patches, 1)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 12))

        ax1.imshow(image)
        ax1.set_title("Original Image")
        ax1.axis('off')

        im = ax2.imshow(projected_image, cmap='viridis')
        # fig.colorbar(im, ax=ax2, label='Value')

        ax2.set_title("similarity Visualization")
        ax2.axis('off')

        plt.figure(dpi=300)
        fig.tight_layout()
        fig.savefig(save_name)


if __name__ == '__main__':
    # HF MODEL
    model = AutoModel.from_pretrained(
        "facebook/dinov3-vitl16-pretrain-lvd1689m",
        device_map="auto",
    )
    id = '9A63BE35027C5531E05351EB1D0A24CD'
    image = Image.open(f'/nethome/atena_projetos/fibz/data/Dataset/images/{id}.png')
    image_tensor = resize_transform(image)
    os.makedirs(f'/nethome/recpinfo/users/fibz/data/visualize/{id}', exist_ok=True)
    with torch.inference_mode():
        feats = model(image_tensor.unsqueeze(0).to("cpu"))
        x = feats.last_hidden_state[0, 5:, :]
        cls = feats.pooler_output
        x = x.to('cpu')
        cls = cls.to('cpu')
    
    print('X', x.shape, 'CLS', cls.shape)
    show_pca(x, image, f'/nethome/recpinfo/users/fibz/data/visualize/{id}/HF_PCA.png')
    show_clssim(x, cls, image, f'/nethome/recpinfo/users/fibz/data/visualize/{id}/HF_CLS.png')

    # LOCAL MODEL
    weight_path = '/nethome/recpinfo/users/fibz/data/checkpoints/dinov3-2/ckpt/11999/consolidated_model/pytorch_model.bin'
    cfg_path = 'dinov3/configs/train/dinov3_vitl16_geo.yaml'
    model = load_trained_model(cfg_path, weight_path)

    with torch.inference_mode():
        outputs = model.forward(image_tensor.unsqueeze(0).to("cpu"), is_training=False, return_grid=True)
        print(outputs.keys())
        cls = outputs['cls'].to('cpu')
        x = outputs['grid'].squeeze(0).to('cpu')
    
    print('X', x.shape, 'CLS', cls.shape)
    show_pca(x, image, f'/nethome/recpinfo/users/fibz/data/visualize/{id}/LOCAL_PCA.png')
    show_clssim(x, cls, image, f'/nethome/recpinfo/users/fibz/data/visualize/{id}/LOCAL_CLS.png')